export enum ProductTypeEnum {
	PACK = "PACK",
	AUDIO = "AUDIO",
	VIDEO = "VIDEO",
	IMAGE = "IMAGE",
	CUSTOM_AUDIO = "CUSTOM_AUDIO",
	CUSTOM_VIDEO = "CUSTOM_VIDEO",
	CUSTOM_IMAGE = "CUSTOM_IMAGE", // Plaquinha
	RENT_A_GIRLFRIEND = "RENT_A_GIRLFRIEND",
	SEXY_VOICE_CALL = "SEXY_VOICE_CALL", // GF
	SEXY_VIDEO_CALL = "SEXY_VIDEO_CALL",
}
